### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by metiftikci** [editorise/editorise#1]
- [ ] Show messages
- [ ] Events / Event Listeners
- [ ] Undo/Redo
- [ ] Show open buffers
- [ ] Show dirty buffers
- [ ] Close all buffers
- [ ] Motions
- [ ] Disable modify
- [x] Copy/Paste
- [x] Find in buffer
- [x] Show Popup
- [x] Line numbers
- [x] Whitespace rendering
